CREATE DATABASE IF NOT EXISTS lowcode_platform DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS nacos_config DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS flowable DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE lowcode_platform;

CREATE TABLE IF NOT EXISTS sys_app (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_name VARCHAR(100) NOT NULL COMMENT '应用名称',
    app_code VARCHAR(50) NOT NULL COMMENT '应用编码',
    app_desc VARCHAR(500) COMMENT '应用描述',
    icon VARCHAR(255) COMMENT '应用图标',
    status TINYINT DEFAULT 1 COMMENT '状态 0禁用 1启用',
    version VARCHAR(20) DEFAULT '1.0.0' COMMENT '版本号',
    deploy_config TEXT COMMENT '部署配置',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记 0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_app_code (app_code),
    KEY idx_app_name (app_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用表';

CREATE TABLE IF NOT EXISTS sys_data_source (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    source_name VARCHAR(100) NOT NULL COMMENT '数据源名称',
    source_code VARCHAR(50) NOT NULL COMMENT '数据源编码',
    db_type VARCHAR(20) NOT NULL COMMENT '数据库类型 mysql postgresql dm',
    host VARCHAR(100) NOT NULL COMMENT '主机地址',
    port INT NOT NULL COMMENT '端口',
    db_name VARCHAR(100) NOT NULL COMMENT '数据库名',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    driver_class VARCHAR(255) COMMENT '驱动类',
    connection_params TEXT COMMENT '连接参数',
    status TINYINT DEFAULT 1 COMMENT '状态 0禁用 1启用',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_code (source_code),
    KEY idx_app_id (app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据源表';

CREATE TABLE IF NOT EXISTS sys_data_model (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    data_source_id BIGINT NOT NULL COMMENT '数据源ID',
    model_name VARCHAR(100) NOT NULL COMMENT '模型名称',
    table_name VARCHAR(100) NOT NULL COMMENT '表名',
    entity_name VARCHAR(100) NOT NULL COMMENT '实体类名',
    model_desc VARCHAR(500) COMMENT '模型描述',
    primary_key_strategy VARCHAR(50) DEFAULT 'AUTO' COMMENT '主键策略 AUTO INPUT UUID',
    logic_delete_field VARCHAR(50) COMMENT '逻辑删除字段',
    version_field VARCHAR(50) COMMENT '乐观锁字段',
    tenant_field VARCHAR(50) COMMENT '租户字段',
    table_charset VARCHAR(20) DEFAULT 'utf8mb4' COMMENT '表字符集',
    table_engine VARCHAR(20) DEFAULT 'InnoDB' COMMENT '表引擎',
    position_x INT DEFAULT 0 COMMENT 'ER图X坐标',
    position_y INT DEFAULT 0 COMMENT 'ER图Y坐标',
    status TINYINT DEFAULT 1 COMMENT '状态 0设计中 1已发布',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_table_name (data_source_id, table_name),
    KEY idx_app_id (app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据模型表';

CREATE TABLE IF NOT EXISTS sys_model_field (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    model_id BIGINT NOT NULL COMMENT '模型ID',
    field_name VARCHAR(50) NOT NULL COMMENT '字段名',
    column_name VARCHAR(50) NOT NULL COMMENT '列名',
    field_type VARCHAR(50) NOT NULL COMMENT '字段类型 STRING NUMBER DATE ENUM REFERENCE',
    java_type VARCHAR(100) NOT NULL COMMENT 'Java类型',
    jdbc_type VARCHAR(50) NOT NULL COMMENT 'JDBC类型',
    length INT DEFAULT 255 COMMENT '长度',
    precision INT DEFAULT 0 COMMENT '精度',
    scale INT DEFAULT 0 COMMENT '小数位数',
    default_value VARCHAR(255) COMMENT '默认值',
    field_comment VARCHAR(255) COMMENT '字段注释',
    is_primary TINYINT DEFAULT 0 COMMENT '是否主键 0否 1是',
    is_required TINYINT DEFAULT 0 COMMENT '是否必填 0否 1是',
    is_unique TINYINT DEFAULT 0 COMMENT '是否唯一 0否 1是',
    is_index TINYINT DEFAULT 0 COMMENT '是否索引 0否 1是',
    is_auto_increment TINYINT DEFAULT 0 COMMENT '是否自增 0否 1是',
    is_logic_delete TINYINT DEFAULT 0 COMMENT '是否逻辑删除 0否 1是',
    is_version TINYINT DEFAULT 0 COMMENT '是否乐观锁 0否 1是',
    is_tenant TINYINT DEFAULT 0 COMMENT '是否租户字段 0否 1是',
    enum_values TEXT COMMENT '枚举值JSON',
    reference_model_id BIGINT COMMENT '关联模型ID',
    reference_field_id BIGINT COMMENT '关联字段ID',
    reference_type VARCHAR(20) COMMENT '关联类型 ONE_TO_ONE ONE_TO_MANY MANY_TO_MANY',
    sort_order INT DEFAULT 0 COMMENT '排序',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    KEY idx_model_id (model_id),
    KEY idx_column_name (model_id, column_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模型字段表';

CREATE TABLE IF NOT EXISTS sys_model_index (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    model_id BIGINT NOT NULL COMMENT '模型ID',
    index_name VARCHAR(100) NOT NULL COMMENT '索引名称',
    index_type VARCHAR(20) DEFAULT 'NORMAL' COMMENT '索引类型 NORMAL UNIQUE FULLTEXT',
    index_fields TEXT NOT NULL COMMENT '索引字段JSON',
    index_comment VARCHAR(255) COMMENT '索引注释',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_index_name (model_id, index_name),
    KEY idx_model_id (model_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模型索引表';

CREATE TABLE IF NOT EXISTS sys_model_relation (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    source_model_id BIGINT NOT NULL COMMENT '源模型ID',
    target_model_id BIGINT NOT NULL COMMENT '目标模型ID',
    relation_type VARCHAR(20) NOT NULL COMMENT '关联类型 ONE_TO_ONE ONE_TO_MANY MANY_TO_MANY',
    source_field_id BIGINT NOT NULL COMMENT '源字段ID',
    target_field_id BIGINT NOT NULL COMMENT '目标字段ID',
    foreign_key_name VARCHAR(100) COMMENT '外键名称',
    on_delete VARCHAR(20) DEFAULT 'RESTRICT' COMMENT '删除策略 CASCADE SET_NULL RESTRICT',
    on_update VARCHAR(20) DEFAULT 'RESTRICT' COMMENT '更新策略 CASCADE SET_NULL RESTRICT',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    KEY idx_app_id (app_id),
    KEY idx_source_model (source_model_id),
    KEY idx_target_model (target_model_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模型关联表';

CREATE TABLE IF NOT EXISTS sys_sql_migration (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    data_source_id BIGINT NOT NULL COMMENT '数据源ID',
    version VARCHAR(20) NOT NULL COMMENT '版本号',
    migration_name VARCHAR(100) NOT NULL COMMENT '迁移名称',
    sql_content TEXT NOT NULL COMMENT 'SQL内容',
    model_changes TEXT COMMENT '模型变更JSON',
    status TINYINT DEFAULT 0 COMMENT '状态 0待执行 1已执行 2执行失败',
    execute_time DATETIME COMMENT '执行时间',
    execute_result TEXT COMMENT '执行结果',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_app_id (app_id),
    KEY idx_data_source (data_source_id),
    KEY idx_version (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SQL迁移表';

CREATE TABLE IF NOT EXISTS sys_page (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    page_name VARCHAR(100) NOT NULL COMMENT '页面名称',
    page_code VARCHAR(50) NOT NULL COMMENT '页面编码',
    page_type VARCHAR(20) DEFAULT 'PC' COMMENT '页面类型 PC MOBILE BOTH',
    page_path VARCHAR(255) COMMENT '页面路由路径',
    layout_type VARCHAR(50) DEFAULT 'FLEX' COMMENT '布局类型 FLEX GRID ABSOLUTE',
    page_config TEXT COMMENT '页面配置JSON',
    page_schema TEXT COMMENT '页面Schema',
    is_home TINYINT DEFAULT 0 COMMENT '是否首页 0否 1是',
    status TINYINT DEFAULT 0 COMMENT '状态 0设计中 1已发布',
    version VARCHAR(20) DEFAULT '1.0.0' COMMENT '版本号',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_page_code (app_id, page_code),
    KEY idx_app_id (app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='页面表';

CREATE TABLE IF NOT EXISTS sys_page_component (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    page_id BIGINT NOT NULL COMMENT '页面ID',
    component_id VARCHAR(50) NOT NULL COMMENT '组件唯一ID',
    component_type VARCHAR(50) NOT NULL COMMENT '组件类型',
    component_name VARCHAR(100) COMMENT '组件名称',
    parent_id VARCHAR(50) COMMENT '父组件ID',
    slot_name VARCHAR(50) COMMENT '插槽名称',
    props_config TEXT COMMENT '属性配置JSON',
    style_config TEXT COMMENT '样式配置JSON',
    event_config TEXT COMMENT '事件配置JSON',
    data_source_config TEXT COMMENT '数据源配置JSON',
    validation_config TEXT COMMENT '校验配置JSON',
    position_x INT COMMENT 'X坐标',
    position_y INT COMMENT 'Y坐标',
    width INT COMMENT '宽度',
    height INT COMMENT '高度',
    sort_order INT DEFAULT 0 COMMENT '排序',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_component_id (page_id, component_id),
    KEY idx_page_id (page_id),
    KEY idx_parent_id (page_id, parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='页面组件表';

CREATE TABLE IF NOT EXISTS sys_component_library (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    component_type VARCHAR(50) NOT NULL COMMENT '组件类型',
    component_name VARCHAR(100) NOT NULL COMMENT '组件名称',
    component_category VARCHAR(50) NOT NULL COMMENT '组件分类 基础 表单 布局 图表 业务',
    icon VARCHAR(255) COMMENT '组件图标',
    description VARCHAR(500) COMMENT '组件描述',
    default_props TEXT COMMENT '默认属性JSON',
    default_style TEXT COMMENT '默认样式JSON',
    prop_schema TEXT COMMENT '属性Schema',
    is_custom TINYINT DEFAULT 0 COMMENT '是否自定义组件 0否 1是',
    component_code TEXT COMMENT '自定义组件代码',
    status TINYINT DEFAULT 1 COMMENT '状态 0禁用 1启用',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_component_type (component_type),
    KEY idx_category (component_category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组件库表';

CREATE TABLE IF NOT EXISTS sys_business_logic (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    logic_name VARCHAR(100) NOT NULL COMMENT '逻辑名称',
    logic_code VARCHAR(50) NOT NULL COMMENT '逻辑编码',
    logic_type VARCHAR(20) DEFAULT 'FLOW' COMMENT '逻辑类型 FLOW API',
    trigger_type VARCHAR(50) COMMENT '触发器类型 TIMER API TABLE_EVENT MANUAL',
    trigger_config TEXT COMMENT '触发器配置JSON',
    flow_graph TEXT COMMENT '流程图JSON',
    flow_nodes TEXT COMMENT '流程节点JSON',
    flow_edges TEXT COMMENT '流程连线JSON',
    variables TEXT COMMENT '变量定义JSON',
    generated_code TEXT COMMENT '生成的代码',
    status TINYINT DEFAULT 0 COMMENT '状态 0设计中 1已发布 2已部署',
    version VARCHAR(20) DEFAULT '1.0.0' COMMENT '版本号',
    deploy_time DATETIME COMMENT '部署时间',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_logic_code (app_id, logic_code),
    KEY idx_app_id (app_id),
    KEY idx_trigger_type (trigger_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='业务逻辑表';

CREATE TABLE IF NOT EXISTS sys_logic_debug (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    logic_id BIGINT NOT NULL COMMENT '逻辑ID',
    debug_session_id VARCHAR(50) NOT NULL COMMENT '调试会话ID',
    current_node_id VARCHAR(50) COMMENT '当前节点ID',
    variables_snapshot TEXT COMMENT '变量快照JSON',
    execution_log TEXT COMMENT '执行日志',
    status VARCHAR(20) DEFAULT 'RUNNING' COMMENT '状态 RUNNING PAUSED FINISHED ERROR',
    breakpoints TEXT COMMENT '断点JSON',
    start_time DATETIME COMMENT '开始时间',
    end_time DATETIME COMMENT '结束时间',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_logic_id (logic_id),
    KEY idx_session_id (debug_session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='逻辑调试表';

CREATE TABLE IF NOT EXISTS sys_workflow_definition (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    process_key VARCHAR(50) NOT NULL COMMENT '流程定义Key',
    process_name VARCHAR(100) NOT NULL COMMENT '流程名称',
    process_desc VARCHAR(500) COMMENT '流程描述',
    bpmn_xml TEXT COMMENT 'BPMN XML内容',
    flow_graph TEXT COMMENT '流程图JSON',
    flowable_deployment_id VARCHAR(64) COMMENT 'Flowable部署ID',
    flowable_process_def_id VARCHAR(64) COMMENT 'Flowable流程定义ID',
    status TINYINT DEFAULT 0 COMMENT '状态 0设计中 1已部署 2已挂起',
    version INT DEFAULT 1 COMMENT '版本号',
    deploy_time DATETIME COMMENT '部署时间',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_process_key (app_id, process_key, version),
    KEY idx_app_id (app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工作流定义表';

CREATE TABLE IF NOT EXISTS sys_generated_code (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    model_id BIGINT COMMENT '模型ID',
    logic_id BIGINT COMMENT '逻辑ID',
    code_type VARCHAR(50) NOT NULL COMMENT '代码类型 ENTITY MAPPER SERVICE CONTROLLER API JS',
    file_path VARCHAR(255) NOT NULL COMMENT '文件路径',
    file_name VARCHAR(100) NOT NULL COMMENT '文件名',
    code_content TEXT COMMENT '代码内容',
    language VARCHAR(20) DEFAULT 'Java' COMMENT '语言',
    version VARCHAR(20) DEFAULT '1.0.0' COMMENT '版本号',
    generated_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '生成时间',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_app_id (app_id),
    KEY idx_model_id (model_id),
    KEY idx_logic_id (logic_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生成代码表';

CREATE TABLE IF NOT EXISTS sys_app_deploy (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    deploy_version VARCHAR(20) NOT NULL COMMENT '部署版本',
    deploy_type VARCHAR(20) DEFAULT 'DOCKER' COMMENT '部署类型 DOCKER K8S',
    deploy_config TEXT COMMENT '部署配置JSON',
    deploy_status VARCHAR(20) DEFAULT 'PENDING' COMMENT '部署状态 PENDING RUNNING SUCCESS FAILED',
    deploy_log TEXT COMMENT '部署日志',
    access_url VARCHAR(255) COMMENT '访问地址',
    start_time DATETIME COMMENT '开始时间',
    end_time DATETIME COMMENT '结束时间',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_app_id (app_id),
    KEY idx_deploy_version (app_id, deploy_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用部署表';

CREATE TABLE IF NOT EXISTS sys_app_template (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    template_name VARCHAR(100) NOT NULL COMMENT '模板名称',
    template_code VARCHAR(50) NOT NULL COMMENT '模板编码',
    template_desc VARCHAR(500) COMMENT '模板描述',
    icon VARCHAR(255) COMMENT '模板图标',
    category VARCHAR(50) COMMENT '分类 oa/crm/inventory/business/system/other',
    tags VARCHAR(255) COMMENT '标签，逗号分隔',
    version VARCHAR(20) DEFAULT '1.0.0' COMMENT '版本号',
    install_count INT DEFAULT 0 COMMENT '安装次数',
    star_count INT DEFAULT 0 COMMENT '收藏/点赞数',
    screenshot VARCHAR(500) COMMENT '截图URL，逗号分隔',
    template_data LONGTEXT COMMENT '模板数据JSON（包含模型/页面/逻辑等完整快照）',
    template_type TINYINT DEFAULT 1 COMMENT '模板类型 0官方 1用户 2团队',
    publisher VARCHAR(50) COMMENT '发布者名称',
    publisher_id BIGINT COMMENT '发布者ID',
    status TINYINT DEFAULT 0 COMMENT '状态 0草稿 1已发布 2已下架',
    publish_time DATETIME COMMENT '发布时间',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记 0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_template_code (template_code),
    KEY idx_category (category),
    KEY idx_template_type (template_type),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用模板表';

INSERT INTO sys_component_library (component_type, component_name, component_category, icon, description, default_props, default_style, prop_schema) VALUES
('Input', '输入框', '表单', 'FormOutlined', '文本输入框', '{"placeholder":"请输入","maxLength":100}', '{"width":"100%"}', '{}'),
('TextArea', '多行文本', '表单', 'FormOutlined', '多行文本输入框', '{"placeholder":"请输入","rows":4}', '{"width":"100%"}', '{}'),
('InputNumber', '数字输入', '表单', 'FormOutlined', '数字输入框', '{"min":0,"precision":2}', '{"width":"100%"}', '{}'),
('Select', '下拉选择', '表单', 'FormOutlined', '下拉选择器', '{"options":[],"placeholder":"请选择"}', '{"width":"100%"}', '{}'),
('DatePicker', '日期选择', '表单', 'CalendarOutlined', '日期选择器', '{"placeholder":"请选择日期"}', '{"width":"100%"}', '{}'),
('TimePicker', '时间选择', '表单', 'ClockCircleOutlined', '时间选择器', '{"placeholder":"请选择时间"}', '{"width":"100%"}', '{}'),
('Checkbox', '复选框', '表单', 'CheckSquareOutlined', '复选框组件', '{"defaultChecked":false}', '{}', '{}'),
('Radio', '单选框', '表单', 'CheckCircleOutlined', '单选框组件', '{"options":[]}', '{}', '{}'),
('Switch', '开关', '表单', 'SwitcherOutlined', '开关组件', '{"defaultChecked":false}', '{}', '{}'),
('Upload', '文件上传', '表单', 'UploadOutlined', '文件上传组件', '{"maxCount":1,"accept":".jpg,.png,.pdf"}', '{}', '{}'),
('Button', '按钮', '基础', 'PlayCircleOutlined', '按钮组件', '{"text":"按钮","type":"primary"}', '{}', '{}'),
('Table', '表格', '展示', 'TableOutlined', '数据表格', '{"columns":[],"dataSource":[]}', '{"width":"100%"}', '{}'),
('Card', '卡片', '布局', 'IdcardOutlined', '卡片容器', '{"title":"卡片标题"}', '{}', '{}'),
('Tabs', '标签页', '布局', 'TabletOutlined', '标签页容器', '{"items":[]}', '{}', '{}'),
('Form', '表单', '表单', 'FormOutlined', '表单容器', '{"labelCol":6,"wrapperCol":18}', '{}', '{}'),
('Divider', '分割线', '布局', 'ColumnHeightOutlined', '分割线组件', '{"orientation":"center"}', '{}', '{}'),
('LineChart', '折线图', '图表', 'LineChartOutlined', '折线图组件', '{"xField":"name","yField":"value"}', '{"width":"100%","height":300}', '{}'),
('BarChart', '柱状图', '图表', 'BarChartOutlined', '柱状图组件', '{"xField":"name","yField":"value"}', '{"width":"100%","height":300}', '{}'),
('PieChart', '饼图', '图表', 'PieChartOutlined', '饼图组件', '{"angleField":"value","colorField":"name"}', '{"width":"100%","height":300}', '{}'),
('Row', '行布局', '布局', 'LayoutOutlined', '行布局容器', '{"gutter":16}', '{}', '{}'),
('Col', '列布局', '布局', 'LayoutOutlined', '列布局容器', '{"span":12}', '{}', '{}');

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    password VARCHAR(100) NOT NULL COMMENT '密码',
    salt VARCHAR(50) NOT NULL COMMENT '盐值',
    nickname VARCHAR(50) COMMENT '昵称',
    avatar VARCHAR(255) COMMENT '头像',
    email VARCHAR(100) COMMENT '邮箱',
    phone VARCHAR(20) COMMENT '手机号',
    status TINYINT DEFAULT 0 COMMENT '状态 0启用 1禁用',
    user_type TINYINT DEFAULT 0 COMMENT '用户类型 0普通用户 1管理员',
    dept_id BIGINT COMMENT '部门ID',
    remark VARCHAR(500) COMMENT '备注',
    last_login_time DATETIME COMMENT '最后登录时间',
    last_login_ip VARCHAR(50) COMMENT '最后登录IP',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_username (username),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    role_name VARCHAR(50) NOT NULL COMMENT '角色名称',
    role_code VARCHAR(50) NOT NULL COMMENT '角色编码',
    role_sort INT DEFAULT 0 COMMENT '排序',
    status TINYINT DEFAULT 0 COMMENT '状态 0启用 1禁用',
    remark VARCHAR(500) COMMENT '备注',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_role_code (role_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

CREATE TABLE IF NOT EXISTS sys_permission (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    parent_id BIGINT DEFAULT 0 COMMENT '父级ID',
    permission_name VARCHAR(50) NOT NULL COMMENT '权限名称',
    permission_code VARCHAR(100) NOT NULL COMMENT '权限编码',
    permission_type TINYINT DEFAULT 1 COMMENT '权限类型 1目录 2菜单 3按钮',
    path VARCHAR(255) COMMENT '路由路径',
    component VARCHAR(255) COMMENT '组件路径',
    icon VARCHAR(50) COMMENT '图标',
    sort INT DEFAULT 0 COMMENT '排序',
    visible TINYINT DEFAULT 0 COMMENT '是否显示 0显示 1隐藏',
    status TINYINT DEFAULT 0 COMMENT '状态 0启用 1禁用',
    remark VARCHAR(500) COMMENT '备注',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_permission_code (permission_code),
    KEY idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限表';

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_role (user_id, role_id),
    KEY idx_user_id (user_id),
    KEY idx_role_id (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联表';

CREATE TABLE IF NOT EXISTS sys_role_permission (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    permission_id BIGINT NOT NULL COMMENT '权限ID',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_role_permission (role_id, permission_id),
    KEY idx_role_id (role_id),
    KEY idx_permission_id (permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限关联表';

CREATE TABLE IF NOT EXISTS sys_oss_file (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    file_name VARCHAR(255) NOT NULL COMMENT '存储文件名',
    original_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    file_suffix VARCHAR(20) COMMENT '文件后缀',
    file_size BIGINT NOT NULL COMMENT '文件大小(字节)',
    content_type VARCHAR(100) COMMENT '内容类型',
    storage_type VARCHAR(20) NOT NULL COMMENT '存储类型 minio aliyun tencent',
    bucket_name VARCHAR(100) NOT NULL COMMENT '存储桶名称',
    file_path VARCHAR(500) NOT NULL COMMENT '文件路径',
    url VARCHAR(500) COMMENT '访问地址',
    md5 VARCHAR(32) COMMENT '文件MD5',
    upload_user_id BIGINT COMMENT '上传用户ID',
    upload_username VARCHAR(50) COMMENT '上传用户名',
    status TINYINT DEFAULT 0 COMMENT '状态 0正常 1已删除',
    remark VARCHAR(500) COMMENT '备注',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    KEY idx_md5 (md5),
    KEY idx_storage_type (storage_type),
    KEY idx_upload_user_id (upload_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OSS文件表';

INSERT INTO sys_user (username, password, salt, nickname, status, user_type, remark) VALUES
('admin', 'e10adc3949ba59abbe56e057f20f883e', 'lowcode-platform', '超级管理员', 0, 1, '系统默认超级管理员账号，密码：123456'),
('user', 'e10adc3949ba59abbe56e057f20f883e', 'lowcode-platform', '普通用户', 0, 0, '系统默认普通用户账号，密码：123456');

INSERT INTO sys_role (role_name, role_code, role_sort, status, remark) VALUES
('超级管理员', 'admin', 1, 0, '拥有所有权限'),
('管理员', 'manager', 2, 0, '拥有大部分管理权限'),
('普通用户', 'user', 3, 0, '普通用户权限');

INSERT INTO sys_user_role (user_id, role_id) VALUES
(1, 1),
(2, 3);

INSERT INTO sys_permission (parent_id, permission_name, permission_code, permission_type, path, component, icon, sort) VALUES
(0, '系统管理', 'system', 1, '/system', '', 'SettingOutlined', 1),
(1, '用户管理', 'system:user', 2, '/system/user', 'system/user/index', 'UserOutlined', 1),
(1, '角色管理', 'system:role', 2, '/system/role', 'system/role/index', 'TeamOutlined', 2),
(1, '权限管理', 'system:permission', 2, '/system/permission', 'system/permission/index', 'SafetyOutlined', 3),
(0, '数据模型', 'model', 1, '/model', '', 'DatabaseOutlined', 2),
(5, '数据源管理', 'model:datasource', 2, '/model/datasource', 'model/datasource/index', 'CloudServerOutlined', 1),
(5, '模型设计', 'model:design', 2, '/model/designer', 'model/designer/index', 'TableOutlined', 2),
(0, '页面设计', 'page', 1, '/page', '', 'LayoutOutlined', 3),
(8, '页面列表', 'page:list', 2, '/page/list', 'page/list/index', 'UnorderedListOutlined', 1),
(8, '页面设计器', 'page:designer', 2, '/page/designer', 'page/designer/index', 'EditOutlined', 2),
(0, '流程编排', 'flow', 1, '/flow', '', 'ApartmentOutlined', 4),
(11, '业务逻辑', 'flow:logic', 2, '/flow/logic', 'flow/logic/index', 'BranchesOutlined', 1),
(11, '工作流设计', 'flow:workflow', 2, '/flow/workflow', 'flow/workflow/index', 'GitBranchOutlined', 2),
(0, '应用管理', 'app', 1, '/app', '', 'AppstoreOutlined', 5),
(14, '应用列表', 'app:list', 2, '/app/list', 'app/list/index', 'AppstoreOutlined', 1),
(14, '应用生成', 'app:generate', 2, '/app/generate', 'app/generate/index', 'CloudDownloadOutlined', 2),
(2, '用户新增', 'system:user:add', 3, '', '', '', 1),
(2, '用户编辑', 'system:user:edit', 3, '', '', '', 2),
(2, '用户删除', 'system:user:delete', 3, '', '', '', 3),
(3, '角色新增', 'system:role:add', 3, '', '', '', 1),
(3, '角色编辑', 'system:role:edit', 3, '', '', '', 2),
(3, '角色删除', 'system:role:delete', 3, '', '', '', 3),
(6, '数据源新增', 'model:datasource:add', 3, '', '', '', 1),
(6, '数据源编辑', 'model:datasource:edit', 3, '', '', '', 2),
(6, '数据源删除', 'model:datasource:delete', 3, '', '', '', 3),
(7, '模型新增', 'model:design:add', 3, '', '', '', 1),
(7, '模型编辑', 'model:design:edit', 3, '', '', '', 2),
(7, '模型删除', 'model:design:delete', 3, '', '', '', 3),
(7, '模型发布', 'model:design:publish', 3, '', '', '', 4),
(9, '页面新增', 'page:list:add', 3, '', '', '', 1),
(9, '页面编辑', 'page:list:edit', 3, '', '', '', 2),
(9, '页面删除', 'page:list:delete', 3, '', '', '', 3),
(9, '页面发布', 'page:list:publish', 3, '', '', '', 4),
(12, '逻辑新增', 'flow:logic:add', 3, '', '', '', 1),
(12, '逻辑编辑', 'flow:logic:edit', 3, '', '', '', 2),
(12, '逻辑删除', 'flow:logic:delete', 3, '', '', '', 3),
(12, '逻辑发布', 'flow:logic:publish', 3, '', '', '', 4),
(13, '流程新增', 'flow:workflow:add', 3, '', '', '', 1),
(13, '流程编辑', 'flow:workflow:edit', 3, '', '', '', 2),
(13, '流程删除', 'flow:workflow:delete', 3, '', '', '', 3),
(13, '流程部署', 'flow:workflow:deploy', 3, '', '', '', 4),
(15, '应用新增', 'app:list:add', 3, '', '', '', 1),
(15, '应用编辑', 'app:list:edit', 3, '', '', '', 2),
(15, '应用删除', 'app:list:delete', 3, '', '', '', 3),
(16, '应用生成', 'app:generate:create', 3, '', '', '', 1),
(16, '应用下载', 'app:generate:download', 3, '', '', '', 2);

INSERT INTO sys_role_permission (role_id, permission_id) VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10),
(1, 11), (1, 12), (1, 13), (1, 14), (1, 15), (1, 16), (1, 17), (1, 18), (1, 19), (1, 20),
(1, 21), (1, 22), (1, 23), (1, 24), (1, 25), (1, 26), (1, 27), (1, 28), (1, 29), (1, 30),
(1, 31), (1, 32), (1, 33), (1, 34), (1, 35), (1, 36), (1, 37), (1, 38), (1, 39), (1, 40),
(1, 41), (1, 42), (1, 43), (1, 44), (1, 45),
(2, 1), (2, 2), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (2, 12), (2, 13), (2, 14), (2, 15), (2, 16),
(3, 5), (3, 8), (3, 11), (3, 14);

ALTER TABLE sys_app ADD COLUMN IF NOT EXISTS template_id BIGINT COMMENT '来源模板ID' AFTER version;
ALTER TABLE sys_app ADD COLUMN IF NOT EXISTS template_version VARCHAR(20) COMMENT '模板版本号' AFTER template_id;
ALTER TABLE sys_app ADD KEY IF NOT EXISTS idx_template_id (template_id);

CREATE TABLE IF NOT EXISTS sys_template_version (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    template_id BIGINT NOT NULL COMMENT '模板ID',
    version VARCHAR(20) NOT NULL COMMENT '版本号',
    change_log VARCHAR(500) COMMENT '更新说明',
    template_data LONGTEXT COMMENT '该版本模板数据快照',
    md5 VARCHAR(32) COMMENT '模板数据MD5签名',
    published_by BIGINT COMMENT '发布人ID',
    publish_time DATETIME COMMENT '发布时间',
    status TINYINT DEFAULT 1 COMMENT '状态 0历史 1当前',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_template_version (template_id, version),
    KEY idx_template_id (template_id),
    KEY idx_publish_time (publish_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模板版本历史表';

CREATE TABLE IF NOT EXISTS sys_app_install (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    template_id BIGINT NOT NULL COMMENT '模板ID',
    template_version VARCHAR(20) NOT NULL COMMENT '安装时模板版本',
    app_id BIGINT NOT NULL COMMENT '安装生成的应用ID',
    user_id BIGINT NOT NULL COMMENT '安装用户ID',
    install_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '安装时间',
    last_update_time DATETIME COMMENT '最后更新时间',
    current_version VARCHAR(20) COMMENT '当前模板版本',
    latest_version VARCHAR(20) COMMENT '最新模板版本',
    has_update TINYINT DEFAULT 0 COMMENT '是否有更新 0否 1是',
    update_diff TEXT COMMENT '更新差异JSON',
    created_by BIGINT COMMENT '创建人',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    PRIMARY KEY (id),
    UNIQUE KEY uk_app_id (app_id),
    KEY idx_template_id (template_id),
    KEY idx_user_id (user_id),
    KEY idx_has_update (has_update)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用安装关联表';
